---
- hosts: web-app-1
  sudo: yes

  vars:
    - WebContent: "Hello to automation BTPN World"
  tasks:
    - name: Install apache2
      apt: name=apache2 update_cache=yes state=present
    - name: Index.html copy to server
      template: src=./htdocs/index.html.j2 dest=/var/www/html/index.html backup=yes 
