---
- hosts: web-app-1
  sudo: yes
  tasks:
    - name: redeploy apache2 to listen on port 8080
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8080" state=present
      notify:
        - restart apache2

    - name: redeploy apache2 to change VirtualHost to port 8080
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8080>" state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
